name: Scheduled Merge Remote Action
on:  
  workflow_dispatch:
jobs:
  merge-upstream:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - name: Merge Upstream
      uses: ethan42/merge-upstream@v4
      with:
        upstream: abuakbar/golang-simple
        upstream-branch: main
        branch: main
  mayhem-analysis:
    uses: ./.github/workflows/mayhem.yml
